name: Deploy Rifa

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Injetar variável CSV_URL
        run: |
          sed -i "s|{{CSV_URL}}|${{ vars.CSV_URL }}|g" index.html

      - name: Deploy (exemplo com GitHub Pages)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
